export interface Prodotto {
  id: string;
  name: string;
  description: string;
  image: string;
  category: "Arredo" | "Illuminazione" | "Tecnologia sostenibile" | "Complementi e accessori" | "Materiali e superfici";
  sustainabilityScore: number;
  materials: string[];
  recyclable: boolean;
  lifespan: string;
}

export const defaultProducts: Prodotto[] = [

  {
    id: "1",
    name: "Sedia Eco 3.0",
    description: "Sedia ergonomica realizzata con plastica riciclata dagli oceani e bambù",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
    category: "Arredo",
    sustainabilityScore: 95,
    materials: ["Plastica oceanica", "Bambù", "Cotone organico"],
    recyclable: true,
    lifespan: "25 anni"
  },
  {
    id: "2",
    name: "Lampada Lumina",
    description: "Lampada ad energia solare con custodia biodegradabile",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80",
    category: "Illuminazione",
    sustainabilityScore: 98,
    materials: ["Composito di micelio", "Vetro riciclato", "Celle solari"],
    recyclable: true,
    lifespan: "15 anni"
  },
  {
    id: "4",
    name: "Portapiante AirPurify",
    description: "Supporto per piante intelligente che migliora la purificazione dell'aria",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
    category: "Complementi e accessori",
    sustainabilityScore: 90,
    materials: ["Legno recuperato", "Alluminio riciclato", "Filtro di muschio"],
    recyclable: true,
    lifespan: "20 anni"
  },
  {
    id: "5",
    name: "Scrivania Nomad",
    description: "Scrivania pieghevole realizzata con materiali sostenibili",
    image: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Bambù", "Composito di canapa", "Acciaio riciclato"],
    recyclable: true,
    lifespan: "15 anni"
  },
  {
    id: "6",
    name: "Altoparlante Sonic",
    description: "Altoparlante ad alta efficienza energetica a impatto negativo di carbonio",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
    category: "Tecnologia sostenibile",
    sustainabilityScore: 85,
    materials: ["Pelle di fungo", "Elettronica riciclata", "Fibra di canapa"],
    recyclable: true,
    lifespan: "12 anni"
  },
  {
    id: "8",
    name: "Sedia T02 Soft",
    description: "Sedia da pranzo versatile e confortevole con design pulito e finiture personalizzabili.",
    image: "https://content.cylindo.com/api/v2/5145/products/T02%20SOFT%20CHAIR/frames/1/T02%20SOFT%20CHAIR.JPG?background=FFFFFF&feature=COMBINATION:1002-006",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno certificato FSC", "Schiuma", "Tessuto riciclato"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {
    id: "9",
    name: "Sedia Palissade Cord",
    description: "Sedia da esterno con telaio in acciaio elegante e finitura resistente alle intemperie.",
    image: "https://img.edilportale.com/product-thumbs/b_Hay_PALISSADE-CORD_pNg3kfVR66.jpeg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Acciaio verniciato a polvere", "Cordone in poliestere per esterni"],
    recyclable: false,
    lifespan: "15 anni",
  },
  {
    id: "10",
    name: "Piastrella Cera Fumo 120x120",
    description: "Piastrella ceramica di alta qualità con finitura fumè, ideale per superfici interne sostenibili.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/02/Cera_Fumo_120x120_-1536x1024.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 87,
    materials: ["Ceramica", "Pigmenti naturali"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "11",
    name: "Sedia CH24",
    description: "Sedia di design scandinavo con struttura in legno di rovere e corda di carta naturale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fchairs%2Fch24%2Foak%2Fch24_oak_oil_papercord_natural_relief.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno di rovere", "Corda di carta naturale"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "21",
    name: "Poltrona CH07",
    description: "Una poltrona lussuosa progettata per comfort e stile.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Floungechairs%2Fch07%2Fch07_lifestyle_new_4.5_.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Legno di quercia", "Corda di carta", "Finitura a olio naturale"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "24",
    name: "Poltrona Oculus CH468",
    description: "Poltrona con struttura in acciaio inossidabile e design minimalista.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Floungechairs%2Fch468%2Fmood%2Foculus-ch468-rustfrit-staal-mood8101_new.png",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Acciaio inossidabile", "Cuscini in tessuto riciclato", "Finitura resistente"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "25",
    name: "Tavolo da pranzo CH006",
    description: "Tavolo elegante in legno di quercia con finitura naturale a olio.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fch006%2Fch36_ch53_oak_oil_papercord_natural_ch006_oak_oil_ek61_o240.jpg",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Legno di quercia", "Corda di carta", "Finitura a olio naturale"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "26",
    name: "Tavolo da pranzo CH327",
    description: "Tavolo rettangolare in legno di rovere massello, perfetto per ambienti eleganti e naturali.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fch327%2Fbt1041_white_ch24_oak_black_ch327_ch24_ch24child_oak_oil_natural_papercord_light.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno di rovere", "Finiture a olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "27",
    name: "Scrivania CH110",
    description: "Scrivania moderna in legno di rovere con struttura in acciaio spazzolato, ideale per uffici sostenibili.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdesk%2Fch110%2Fch111_steel_sif90_ch110_oak_oil_steel_v2.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "28",
    name: "Tavolino CH008 Teak",
    description: "Tavolino rotondo in teak e rovere, perfetto per soggiorni raffinati con un tocco nordico.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch008%2Fch22_teak_oak_oil_papercord_natural_ch008_teak_oak_oil_o78_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Teak", "Rovere", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "29",
    name: "Tavolino CH008 Noce",
    description: "Versione in noce del tavolino CH008, con finitura naturale per un look caldo e accogliente.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch008%2Fch008-walnut-gallery-3.jpg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Noce", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "30",
    name: "Tavolino CH417",
    description: "Tavolino moderno con piano in laminato nero e base in acciaio inox, funzionale e minimale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch417%2Fbakkebord-sort-laminat-rustfrit-staal.png",
    category: "Arredo",
    sustainabilityScore: 85,
    materials: ["Laminato", "Acciaio inox"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "31",
    name: "Tavolino CH415",
    description: "Tavolino in legno di rovere con finitura sapone, design semplice e raffinato per ogni ambiente.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch415%2Fch004_oak_soap_v3.jpg",
    category: "Arredo",
    sustainabilityScore: 86,
    materials: ["Rovere", "Finitura sapone"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "32",
    name: "Scrivania AB019",
    description: "Scrivania compatta con struttura in acciaio nero e legno di rovere, perfetta per spazi di lavoro essenziali.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdesk%2Fab019%2Fab019_ab020d_ab020s_oak_oil_vla26t_oak_lacquer_steel_black_mo310_black_light.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Acciaio verniciato nero"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "33",
    name: "Panca BM0489L",
    description: "Panca in rovere con seduta intrecciata in corda naturale, perfetta per ambienti eleganti o d'ingresso.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fbm0489%2Fbm0489l_oak_oil_papercord_natural_bm0555_160_oak_oil_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Rovere", "Corda naturale", "Finitura a olio"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "34",
    name: "Tavolo da pranzo E020",
    description: "Tavolo da pranzo moderno in rovere con piano in laminato bianco e gambe in acciaio.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fe020-1100%2Fe005_oak_whiteoil_clara144_e020_o110_oak_oil_laminate_white_steel_e005_oak_oil_thor310_80280042_80280022.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Laminato", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "35",
    name: "Tavolino ML10097",
    description: "Tavolino rotondo in legno di quercia con finitura a olio, ispirato al design egizio tradizionale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fml10097%2Faegypterbordet-eg-olie-dia-85.png",
    category: "Arredo",
    sustainabilityScore: 86,
    materials: ["Quercia", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "36",
    name: "Sedia da esterno AH604",
    description: "Sedia pieghevole in teak non trattato, resistente agli agenti atmosferici, ideale per esterni.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah604%2Fah604_teak_untreated_v3.jpg",
    category: "Arredo", // Nota: ho mantenuto "Arredo" invece di "Outdoor" per coerenza con le categorie richieste
    sustainabilityScore: 90,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "37",
    name: "Poltrona da esterno AH603",
    description: "Poltrona da esterno in teak, comoda e robusta, pensata per il relax all'aperto.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah603%2Fah603_teak_untreated_v1.jpg",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "38",
    name: "Tavolo da esterno AH701",
    description: "Tavolo basso da esterno in teak, perfetto per accompagnare sedute lounge e relax estivo.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah701%2Fah701_teak_untreated_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "39",
    name: "Altalena da esterno BK13",
    description: "Altalena a dondolo da giardino in teak con cuscino, per un relax elegante all'aria aperta.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fbk13%2Fkjaer_bk13-swing-sofa_cushion_untreated_teak_side.png",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Teak non trattato", "Tessuto per esterni"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "40",
    name: "Lettino da esterno BK14",
    description: "Lettino da esterno in teak non trattato con tela in canvas, perfetto per il relax in giardino o a bordo piscina.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fbk14%2Fbk14_teak_untreated_canvas5453.jpg",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Teak non trattato", "Canvas"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "41",
    name: "Divano da esterno EOOS 3 posti",
    description: "Composizione modulare da esterno in teak con cuscini in tessuti outdoor resistenti, ideale per zone lounge all'aperto.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Feoos-3-seater-with-lounge%2Fe541_e511_e023_teak_untreated_panamaalga_lifeoat_cu_ritmolaguna_lisoduna.jpg",
    category: "Arredo",
    sustainabilityScore: 93,
    materials: ["Teak non trattato", "Tessuti outdoor"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "42",
    name: "Vaso Nuvole Small (Nason Moretti per Carl Hansen)",
    description: "Vaso in vetro di Murano grigio, realizzato artigianalmente secondo la tradizione veneziana.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Faccessories%2Fnason-moretti%2F80470140-nason-moretti-murano---vase-nuvole-small---grey.png",
    category: "Complementi e accessori",
    sustainabilityScore: 85,
    materials: ["Vetro di Murano"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "43",
    name: "Sgabello Alder Terracotta",
    description: "Sgabello moderno in materiale riciclato con finitura terracotta, ideale per cucine o spazi informali.",
    image: "https://materdesign.com/cdn/shop/files/Mater_30204_AlderStool_Terracotta_Front_copy_1024x1024.jpg?v=1718783310",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Plastica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "44",
    name: "Lampada a sospensione Terho Medium",
    description: "Lampada in legno e vetro opalino ispirata alla forma delle ghiande, perfetta per interni naturali.",
    image: "https://materdesign.com/cdn/shop/products/02302_Terho_Medium_1ae47786-bc9d-43ed-9ff3-82a9e9299a4d_1024x1024.jpg?v=1517326609",
    category: "Illuminazione",
    sustainabilityScore: 90,
    materials: ["Legno certificato FSC", "Vetro soffiato"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "45",
    name: "Sedie Ray Family",
    description: "Sedute moderne realizzate con plastica riciclata, dal design ergonomico e minimale.",
    image: "https://materdesign.com/cdn/shop/products/Ray_Family_new_6fe530a8-aaec-45f9-8c86-9b17c8f66c0f_1024x1024.png?v=1565612719",
    category: "Arredo",
    sustainabilityScore: 94,
    materials: ["Plastica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "46",
    name: "Tavolino basso da esterno Ocean",
    description: "Tavolino in plastica riciclata e acciaio, pensato per ambienti outdoor sostenibili e moderni.",
    image: "https://materdesign.com/cdn/shop/files/MATER__3_acfaba63-c3d0-4b4e-88f4-19d15372fa08_1024x1024.jpg?v=1738320091",
    category: "Arredo",
    sustainabilityScore: 95,
    materials: ["Plastica oceanica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  }
];
