export interface Product {
  id: string;
  name: string;
  description: string;
  image: string;
  category: "Arredo" | "Illuminazione" | "Tecnologia sostenibile" | "Complementi e accessori" | "Materiali e superfici";
  sustainabilityScore: number;
  materials: string[];
  recyclable: boolean;
  lifespan: string;
}

export const defaultProducts: Product[] = [

  {
    id: "1",
    name: "Sedia Eco 3.0",
    description: "Sedia ergonomica realizzata con plastica riciclata dagli oceani e bambù",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
    category: "Arredo",
    sustainabilityScore: 95,
    materials: ["Plastica oceanica", "Bambù", "Cotone organico"],
    recyclable: true,
    lifespan: "25 anni"
  },
  {
    id: "2",
    name: "Lampada Lumina",
    description: "Lampada ad energia solare con custodia biodegradabile",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80",
    category: "Illuminazione",
    sustainabilityScore: 98,
    materials: ["Composito di micelio", "Vetro riciclato", "Celle solari"],
    recyclable: true,
    lifespan: "15 anni"
  },
  {
    id: "3",
    name: "Tavolo Vitra - composizione domestica",
    description: "Tavolo da pranzo Vitra in un ambiente domestico accogliente e contemporaneo.",
    image: "https://static.vitra.com/media-resized/Pd5JWD38RwS1WRdulNmoLN2jHLVAyOAWeITbiJSY8ZI/fill/1440/810/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzk0NzA4Mjkvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC84NzExMzcyMi5qcGc.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno", "Acciaio verniciato"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "4",
    name: "Portapiante AirPurify",
    description: "Supporto per piante intelligente che migliora la purificazione dell'aria",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
    category: "Complementi e accessori",
    sustainabilityScore: 90,
    materials: ["Legno recuperato", "Alluminio riciclato", "Filtro di muschio"],
    recyclable: true,
    lifespan: "20 anni"
  },
  {
    id: "5",
    name: "Scrivania Nomad",
    description: "Scrivania pieghevole realizzata con materiali sostenibili",
    image: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Bambù", "Composito di canapa", "Acciaio riciclato"],
    recyclable: true,
    lifespan: "15 anni"
  },
  {
    id: "6",
    name: "Altoparlante Sonic",
    description: "Altoparlante ad alta efficienza energetica a impatto negativo di carbonio",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
    category: "Tecnologia sostenibile",
    sustainabilityScore: 85,
    materials: ["Pelle di fungo", "Elettronica riciclata", "Fibra di canapa"],
    recyclable: true,
    lifespan: "12 anni"
  },
  {
    id: "8",
    name: "Sedia T02 Soft",
    description: "Sedia da pranzo versatile e confortevole con design pulito e finiture personalizzabili.",
    image: "https://content.cylindo.com/api/v2/5145/products/T02%20SOFT%20CHAIR/frames/1/T02%20SOFT%20CHAIR.JPG?background=FFFFFF&feature=COMBINATION:1002-006",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno certificato FSC", "Schiuma", "Tessuto riciclato"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {
    id: "9",
    name: "Sedia Palissade Cord",
    description: "Sedia da esterno con telaio in acciaio elegante e finitura resistente alle intemperie.",
    image: "https://img.edilportale.com/product-thumbs/b_Hay_PALISSADE-CORD_pNg3kfVR66.jpeg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Acciaio verniciato a polvere", "Cordone in poliestere per esterni"],
    recyclable: false,
    lifespan: "15 anni",
  },
  {
    id: "10",
    name: "Piastrella Cera Fumo 120x120",
    description: "Piastrella ceramica di alta qualità con finitura fumè, ideale per superfici interne sostenibili.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/02/Cera_Fumo_120x120_-1536x1024.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 87,
    materials: ["Ceramica", "Pigmenti naturali"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "11",
    name: "Sedia CH24",
    description: "Sedia di design scandinavo con struttura in legno di rovere e corda di carta naturale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fchairs%2Fch24%2Foak%2Fch24_oak_oil_papercord_natural_relief.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno di rovere", "Corda di carta naturale"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "12",
    name: "Balder D",
    description: "Variante Balder D, superficie tessile con aspetto grezzo e moderno.",
    image: "https://cdn.tapetender70er.de/media/image/9c/48/9a/Balder-D_106184_2880x1440@2x.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 92,
    materials: ["Fibre naturali", "Inchiostri a base d'acqua"],
    recyclable: true,
    lifespan: "12 anni"
  },
  {
    id: "13",
   name: "Balder A",
    description: "Carta da parati Balder A con finitura materica e tono caldo.",
   image: "https://cdn.tapetender70er.de/media/image/d3/45/d9/106184-A_Balder_2880x1440@2x.jpg",
    category: "Materiali e superfici",
   sustainabilityScore: 92,
   materials: ["Fibre naturali", "Inchiostri a base d'acqua"],
   recyclable: true,
   lifespan: "12 anni"
  },
  {
    id: "14",
   name: "Norana C",
    description: "Carta da parati Norana C, fantasia astratta con tonalità sobrie.",
   image: "https://cdn.tapetender70er.de/media/image/88/ac/6b/Norana-C_452814_2880x1440@2x.jpg",
    category: "Materiali e superfici",
   sustainabilityScore: 87,
   materials: ["Carta FSC", "Colori a basso impatto ambientale"],
   recyclable: true,
   lifespan: "10 anni"
  },
  {
    id: "21",
    name: "Poltrona CH07",
    description: "Una poltrona lussuosa progettata per comfort e stile.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Floungechairs%2Fch07%2Fch07_lifestyle_new_4.5_.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Legno di quercia", "Corda di carta", "Finitura a olio naturale"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "24",
    name: "Poltrona Oculus CH468",
    description: "Poltrona con struttura in acciaio inossidabile e design minimalista.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Floungechairs%2Fch468%2Fmood%2Foculus-ch468-rustfrit-staal-mood8101_new.png",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Acciaio inossidabile", "Cuscini in tessuto riciclato", "Finitura resistente"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "25",
    name: "Tavolo da pranzo CH006",
    description: "Tavolo elegante in legno di quercia con finitura naturale a olio.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fch006%2Fch36_ch53_oak_oil_papercord_natural_ch006_oak_oil_ek61_o240.jpg",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Legno di quercia", "Corda di carta", "Finitura a olio naturale"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "26",
    name: "Tavolo da pranzo CH327",
    description: "Tavolo rettangolare in legno di rovere massello, perfetto per ambienti eleganti e naturali.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fch327%2Fbt1041_white_ch24_oak_black_ch327_ch24_ch24child_oak_oil_natural_papercord_light.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno di rovere", "Finiture a olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "27",
    name: "Scrivania CH110",
    description: "Scrivania moderna in legno di rovere con struttura in acciaio spazzolato, ideale per uffici sostenibili.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdesk%2Fch110%2Fch111_steel_sif90_ch110_oak_oil_steel_v2.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "28",
    name: "Tavolino CH008 Teak",
    description: "Tavolino rotondo in teak e rovere, perfetto per soggiorni raffinati con un tocco nordico.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch008%2Fch22_teak_oak_oil_papercord_natural_ch008_teak_oak_oil_o78_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Teak", "Rovere", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "29",
    name: "Tavolino CH008 Noce",
    description: "Versione in noce del tavolino CH008, con finitura naturale per un look caldo e accogliente.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch008%2Fch008-walnut-gallery-3.jpg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Noce", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "30",
    name: "Tavolino CH417",
    description: "Tavolino moderno con piano in laminato nero e base in acciaio inox, funzionale e minimale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch417%2Fbakkebord-sort-laminat-rustfrit-staal.png",
    category: "Arredo",
    sustainabilityScore: 85,
    materials: ["Laminato", "Acciaio inox"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "31",
    name: "Tavolino CH415",
    description: "Tavolino in legno di rovere con finitura sapone, design semplice e raffinato per ogni ambiente.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1920,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fch415%2Fch004_oak_soap_v3.jpg",
    category: "Arredo",
    sustainabilityScore: 86,
    materials: ["Rovere", "Finitura sapone"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "32",
    name: "Scrivania AB019",
    description: "Scrivania compatta con struttura in acciaio nero e legno di rovere, perfetta per spazi di lavoro essenziali.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdesk%2Fab019%2Fab019_ab020d_ab020s_oak_oil_vla26t_oak_lacquer_steel_black_mo310_black_light.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Acciaio verniciato nero"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "33",
    name: "Panca BM0489L",
    description: "Panca in rovere con seduta intrecciata in corda naturale, perfetta per ambienti eleganti o d'ingresso.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fbm0489%2Fbm0489l_oak_oil_papercord_natural_bm0555_160_oak_oil_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Rovere", "Corda naturale", "Finitura a olio"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "34",
    name: "Tavolo da pranzo E020",
    description: "Tavolo da pranzo moderno in rovere con piano in laminato bianco e gambe in acciaio.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fdining-tables%2Fe020-1100%2Fe005_oak_whiteoil_clara144_e020_o110_oak_oil_laminate_white_steel_e005_oak_oil_thor310_80280042_80280022.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Rovere", "Laminato", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "35",
    name: "Tavolino ML10097",
    description: "Tavolino rotondo in legno di quercia con finitura a olio, ispirato al design egizio tradizionale.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Fcoffee-tables%2Fml10097%2Faegypterbordet-eg-olie-dia-85.png",
    category: "Arredo",
    sustainabilityScore: 86,
    materials: ["Quercia", "Olio naturale"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "36",
    name: "Sedia da esterno AH604",
    description: "Sedia pieghevole in teak non trattato, resistente agli agenti atmosferici, ideale per esterni.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah604%2Fah604_teak_untreated_v3.jpg",
    category: "Arredo", // Nota: ho mantenuto "Arredo" invece di "Outdoor" per coerenza con le categorie richieste
    sustainabilityScore: 90,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "37",
    name: "Poltrona da esterno AH603",
    description: "Poltrona da esterno in teak, comoda e robusta, pensata per il relax all'aperto.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah603%2Fah603_teak_untreated_v1.jpg",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  { //cambiato
    id: "38",
    name: "Panche esterne",
    description: "Panche esterne in teak, perfetto per accompagnare sedute lounge e relax estivo.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fah701%2Fah701_teak_untreated_detail.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Teak non trattato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "39",
    name: "Altalena da esterno BK13",
    description: "Altalena a dondolo da giardino in teak con cuscino, per un relax elegante all'aria aperta.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fbk13%2Fkjaer_bk13-swing-sofa_cushion_untreated_teak_side.png",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Teak non trattato", "Tessuto per esterni"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "40",
    name: "Lettino da esterno BK14",
    description: "Lettino da esterno in teak non trattato con tela in canvas, perfetto per il relax in giardino o a bordo piscina.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Fbk14%2Fbk14_teak_untreated_canvas5453.jpg",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Teak non trattato", "Canvas"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "41",
    name: "Divano da esterno EOOS 3 posti",
    description: "Composizione modulare da esterno in teak con cuscini in tessuti outdoor resistenti, ideale per zone lounge all'aperto.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_640,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Foutdoor-furniture%2Feoos-3-seater-with-lounge%2Fe541_e511_e023_teak_untreated_panamaalga_lifeoat_cu_ritmolaguna_lisoduna.jpg",
    category: "Arredo",
    sustainabilityScore: 93,
    materials: ["Teak non trattato", "Tessuti outdoor"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "42",
    name: "Vaso Nuvole Small (Nason Moretti per Carl Hansen)",
    description: "Vaso in vetro di Murano grigio, realizzato artigianalmente secondo la tradizione veneziana.",
    image: "https://res.cloudinary.com/dfwzl0ito/image/fetch/c_scale,w_1200,f_auto/https%3A%2F%2Fadmincms.carlhansen.com%2Fglobalassets%2Fproducts%2Faccessories%2Fnason-moretti%2F80470140-nason-moretti-murano---vase-nuvole-small---grey.png",
    category: "Complementi e accessori",
    sustainabilityScore: 85,
    materials: ["Vetro di Murano"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "43",
    name: "Sgabello Alder Terracotta",
    description: "Sgabello moderno in materiale riciclato con finitura terracotta, ideale per cucine o spazi informali.",
    image: "https://materdesign.com/cdn/shop/files/Mater_30204_AlderStool_Terracotta_Front_copy_1024x1024.jpg?v=1718783310",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Plastica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "44",
    name: "Lampada a sospensione Terho Medium",
    description: "Lampada in legno e vetro opalino ispirata alla forma delle ghiande, perfetta per interni naturali.",
    image: "https://materdesign.com/cdn/shop/products/02302_Terho_Medium_1ae47786-bc9d-43ed-9ff3-82a9e9299a4d_1024x1024.jpg?v=1517326609",
    category: "Illuminazione",
    sustainabilityScore: 90,
    materials: ["Legno certificato FSC", "Vetro soffiato"],
    recyclable: true,
    lifespan: "25 anni",
  },
  { //cambiato 
    id: "45",
    name: "Lampade da Design",
    description: "Lampada realizzata con plastica riciclata, dal design ergonomico e minimale.",
    image: "https://materdesign.com/cdn/shop/products/Ray_Family_new_6fe530a8-aaec-45f9-8c86-9b17c8f66c0f_1024x1024.png?v=1565612719",
    category: "Illuminazione",
    sustainabilityScore: 94,
    materials: ["Plastica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  { //cambiato 
    id: "46",
    name: "Lampade da esterno",
    description: "Lampada pensata per ambienti outdoor sostenibili e moderni.",
    image: "https://materdesign.com/cdn/shop/files/MATER__3_acfaba63-c3d0-4b4e-88f4-19d15372fa08_1024x1024.jpg?v=1738320091",
    category: "Illuminazione",
    sustainabilityScore: 95,
    materials: ["Plastica oceanica riciclata", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "47",
    name: "Sedia Cross",
    description: "Sedia in legno massello con struttura incrociata, perfetta per ambienti moderni e sostenibili.",
    image: "https://taktcph.com/wp-content/uploads/2022/11/lifestylecrosschair221114.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno massello", "Componenti metalliche"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "48",
    name: "Poltrona lounge imbottita",
    description: "Poltrona in legno e tessuto dal design minimalista, ideale per il relax e il comfort.",
    image: "https://content.cylindo.com/api/v2/5145/products/T04%20SOFT%20LOUNGE%20CHAIR/frames/1/T04%20SOFT%20LOUNGE%20CHAIR.JPG?background=FFFFFF&feature=COMBINATION:1004-006",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Legno certificato FSC", "Tessuto riciclato"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "49",
    name: "Poltrona lounge chiara",
    description: "Poltrona lounge con struttura in legno chiaro e rivestimento neutro, dal look moderno e rilassato.",
    image: "https://taktcph.com/wp-content/uploads/2023/08/2023-08-22-takt157222split-960x1080.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 92,
    materials: ["Legno di rovere", "Tessuto sostenibile"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "51",
    name: "Tavolino laterale Sling - ambientazione",
    description: "Tavolino laterale leggero e compatto, con design ideale per spazi contenuti.",
    image: "https://taktcph.com/wp-content/uploads/2020/03/lifestyle-split-slingsidetable.webp",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Acciaio verniciato", "MDF sostenibile"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {
    id: "52",
    name: "Tavolino laterale Sling - dettaglio",
    description: "Dettaglio della struttura metallica del tavolino Sling, con focus sulla qualità costruttiva.",
    image: "https://taktcph.com/wp-content/uploads/2020/03/gallery-0008-takt-sling-special-angles-03.webp",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Acciaio", "MDF a bassa emissione"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {
    id: "53",
    name: "Tavolino Sling",
    description: "Tavolino compatto con gambe in metallo e piano circolare, dal design essenziale.",
    image: "https://content.cylindo.com/api/v2/5145/products/T08%20SLING%20SIDE%20TABLE/frames/1/T08%20SLING%20SIDE%20TABLE.JPG?background=FFFFFF&feature=COMBINATION:1008-003",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Metallo riciclato", "Legno stratificato"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {//cambiato
    id: "54",
    name: "Cucina - ambientazione",
    description: "Cucina moderna, perfetta per la zona giorno o l’ambiente di lavoro.",
    image: "https://taktcph.com/wp-content/uploads/2022/09/splitmodule-0003-2022-06-01-takt-y2126341.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno", "Imbottitura riciclata"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {//cambiato
    id: "55",
    name: "Appendiabiti", 
    description: "Appendiabiti modulare in legno, ideale per ingressi e spazi di lavoro.",
    image: "https://taktcph.com/wp-content/uploads/2022/09/splitmodule-0007-2022-06-01-takt-y2126488.png.webp",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Struttura in legno", "Componenti modulari"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "56",
    name: "Sedia Soft",
    description: "Sedia ergonomica dal profilo elegante, realizzata con materiali sostenibili.",
    image: "https://content.cylindo.com/api/v2/5145/products/T02%20SOFT%20CHAIR/frames/1/T02%20SOFT%20CHAIR.JPG?background=FFFFFF&feature=COMBINATION:1002-006",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno FSC", "Rivestimento in tessuto"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "57",
    name: "Sedia Soft - ambientazione showroom",
    description: "Sedia Soft in un ambiente domestico, che mostra la sua versatilità e semplicità.",
    image: "https://taktcph.com/wp-content/uploads/2020/02/showroomhomesoftchair25022020.webp",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno", "Tessuto"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "58",
    name: "Collezione Soft in rovere",
    description: "Collezione di sedute in rovere naturale con linee morbide e dettagli raffinati.",
    image: "https://taktcph.com/wp-content/uploads/2020/03/softoakcollection-0002-takt-soft-oak-image-03-v1.webp",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Rovere europeo", "Tessuto sostenibile"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "59",
    name: "Sgabello Cross Bar",
    description: "Sgabello alto con struttura incrociata, perfetto per isole cucina e spazi bar.",
    image: "https://content.cylindo.com/api/v2/5145/products/T16%20CROSS%20BAR%20CHAIR/frames/1/T16%20CROSS%20BAR%20CHAIR.JPG?background=FFFFFF&feature=COMBINATION:1016-013",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Legno massello", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "60",
    name: "Sgabello Cross Bar - vista laterale",
    description: "Sgabello alto con struttura in legno e seduta sagomata, dal design essenziale e nordico.",
    image: "https://taktcph.com/wp-content/uploads/2022/01/splitmodule-0004-2021-06-21-takt102355crossbarchair.png",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Legno massello", "Componenti in acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "61",
    name: "Sgabello Cross Bar - due altezze",
    description: "Due versioni dello sgabello Cross Bar, adatte a diverse altezze di piano o banco.",
    image: "https://taktcph.com/wp-content/uploads/2022/01/splitmodule-0004-2021-06-21-takt102355crossbarchairheights-1.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Legno certificato FSC", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "62",
    name: "Sgabello Cross Bar in veranda",
    description: "Sgabello in ambientazione veranda, che esalta la sua versatilità per uso interno ed esterno coperto.",
    image: "https://taktcph.com/wp-content/uploads/2022/01/splitmodule-0014-2021-11-10-takt-veranda1860-1crossbarchair.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Legno", "Acciaio verniciato"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "63",
    name: "Sgabello Cross Bar - render trasparente",
    description: "Render tecnico trasparente dello sgabello, evidenzia la struttura e la qualità dei materiali.",
    image: "https://taktcph.com/wp-content/uploads/2022/01/splitmodule-0004-2021-06-21-takt102355crossbarchairtransparency.png.webp",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Legno massello", "Finiture metalliche"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "64",
    name: "Tavolo Studio",
    description: "Tavolo minimalista per studio o sala da pranzo, con piano sottile e gambe affusolate.",
    image: "https://content.cylindo.com/api/v2/5145/products/T25%20STUDIO%20TABLE/frames/1/T25%20STUDIO%20TABLE.JPG?background=FFFFFF&feature=COMBINATION:1025-001-002",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno di frassino", "Finiture ecologiche"],
    recyclable: true,
    lifespan: "25 anni",
  },
  { //cambiato
    id: "65",
    name: "Sedia imbottita Soft - ambientazione chiara",
    description: "Sedia imbottita dal profilo essenziale, ideale per ingressi o per la sala da pranzo.",
    image: "https://taktcph.com/wp-content/uploads/2025/02/mobile-format-960x1080.webp",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno", "Tessuto riciclato"],
    recyclable: true,
    lifespan: "20 anni",
  },
  { //cambiato
    id: "66",
    name: "Sedia Soft - ambientazione scura",
    description: "Versione scura della sedia Soft, perfetta per ambienti contemporanei e raffinati.",
    image: "https://taktcph.com/wp-content/uploads/2025/02/2024-06-17-takt174994-1-scaled-e1740654474717-960x1080.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno tinto", "Tessuti sostenibili"],
    recyclable: true,
    lifespan: "20 anni",
  },
  { //cambiato
    id: "67",
    name: "Scrivania Soft - vista dinamica",
    description: "Vista dinamica della scrivania Soft, con animazione che ne evidenzia la forma compatta e robusta.",
    image: "https://taktcph.com/wp-content/uploads/2025/02/ezgif.com-webp-maker-960x1080.webp",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno", "Rivestimento eco"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "68",
    name: "Panca Soft",
    description: "Panca semplice e versatile, perfetta per ogni ambiente grazie al suo stile sobrio.",
    image: "https://content.cylindo.com/api/v2/5145/products/T05%20SOFT%20BENCH/frames/1/T05%20SOFT%20BENCH.JPG?background=FFFFFF&feature=COMBINATION:1005-010",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno FSC", "Tessuto riciclato"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "69",
    name: "Panca Soft - lifestyle",
    description: "Panca Soft in ambientazione domestica, mostra la sua funzionalità e integrabilità.",
    image: "https://taktcph.com/wp-content/uploads/2019/10/t05-lifestylehouse02.webp",
    category: "Arredo",
    sustainabilityScore: 91,
    materials: ["Legno", "Tessuto ecologico"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "70",
    name: "Divano Spoke",
    description: "Divano elegante con struttura a raggi visibili, unisce comfort e leggerezza estetica.",
    image: "https://content.cylindo.com/api/v2/5145/products/T%2019%20SPOKE%20SOFA/frames/1/T%2019%20SPOKE%20SOFA.JPG?background=FFFFFF&feature=COMBINATION:1019-001-048",
    category: "Arredo",
    sustainabilityScore: 93,
    materials: ["Legno massello", "Imbottitura in materiale riciclato"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "71",
    name: "Divano Spoke - ambientazione chiara",
    description: "Divano Spoke inserito in uno spazio living luminoso, esalta la sua estetica nordica.",
    image: "https://taktcph.com/wp-content/uploads/2023/08/galleryspokesofa230831-0001-2023-08-22-takt157132.jpg.webp",
    category: "Arredo",
    sustainabilityScore: 93,
    materials: ["Legno massello", "Tessuti riciclati"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "72",
    name: "Divano Spoke - vista tecnica",
    description: "Render tecnico del divano Spoke, mostra dettagli costruttivi e proporzioni.",
    image: "https://taktcph.com/wp-content/uploads/2023/05/splitmodulespokesofa230519-0001s-0012-m-2.png.webp",
    category: "Arredo",
    sustainabilityScore: 93,
    materials: ["Legno", "Componenti tessili sostenibili"],
    recyclable: true,
    lifespan: "25 anni",
  },
  {
    id: "73",
    name: "Piastrella effetto pietra - Hero",
    description: "Superficie ceramica ad effetto pietra naturale, per ambienti moderni e minimal.",
    image: "https://www.refin-ceramic-tiles.com/files/2025/04/HERO-1920x1012.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 90,
    materials: ["Gres porcellanato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "74",
    name: "Piastrella decorativa - Reliefs",
    description: "Piastrella ceramica tridimensionale, ideale per pareti d'accento e rivestimenti creativi.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/09/Slider-Reliefs-1920x1012.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 88,
    materials: ["Gres porcellanato strutturato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "75",
    name: "Piastrella effetto legno - Eik",
    description: "Gres porcellanato con venature ispirate al legno naturale, resistente e versatile.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/09/Slider-Eik-2-1920x1012.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 92,
    materials: ["Gres porcellanato"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "76",
    name: "Piastrella effetto cemento - Etherea",
    description: "Superficie ceramica ispirata all'estetica del cemento, sobria e moderna.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/09/Slider-Etherea-1920x1012.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 89,
    materials: ["Gres porcellanato opaco"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "77",
    name: "Piastrella effetto battuto - Beat",
    description: "Ceramica con texture battuta, perfetta per spazi contemporanei e resistenti al calpestio.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/04/beat-in-home-1920x1012.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 91,
    materials: ["Gres porcellanato tecnico"],
    recyclable: true,
    lifespan: "30 anni",
  },
  { //cambiato
    id: "78",
    name: "Piastrella effetto cemento - Affrescati Lapis",
    description: "Piastrella in cemento, con tonalità profonde e materiche.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/02/Affrescati_Lapis_120x120_still_life_01.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 90,
    materials: ["Gres porcellanato smaltato", "cemento"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "79",
    name: "Piastrella lucida - Canal Grande Moro",
    description: "Piastrella ad effetto marmo lucido, elegante e riflettente, per ambienti di pregio.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/02/Canal-Grande_Moro_75x150_Lucido_amb02.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 88,
    materials: ["Gres lucido a specchio"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "80",
    name: "Piastrella naturale - Namib Dune",
    description: "Piastrella dai toni sabbiosi ispirata ai deserti, ideale per pavimentazioni soft.",
    image: "https://www.refin-ceramic-tiles.com/wp-content/uploads/2024/02/Namib_Dune_120x120.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 90,
    materials: ["Gres porcellanato naturale"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "81",
    name: "Piastrella effetto pietra - Blended Natural",
    description: "Piastrella effetto pietra naturale, perfetta per ambienti rustici e raffinati.",
    image: "https://www.refin-ceramic-tiles.com/file/1680x0/ambientazioni/_HEADER/Blended_Natural_60x120_Amb_02_Header.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 89,
    materials: ["Gres effetto pietra"],
    recyclable: true,
    lifespan: "30 anni",
  },
  {
    id: "82",
    name: "Piastrella effetto cemento - Block Mist",
    description: "Superficie ceramica effetto cemento opaco, adatta a spazi industriali e moderni.",
    image: "https://www.refin-ceramic-tiles.com/file/1680x0/ambientazioni/_HEADER/Block-Mist-Soft-75x150.jpg",
    category: "Materiali e superfici",
    sustainabilityScore: 89,
    materials: ["Gres porcellanato opaco"],
    recyclable: true,
    lifespan: "30 anni",
  },
  { //cambiato
    id: "83",
    name: "Panca Palissade Cord",
    description: "Panca outdoor intrecciata con corde resistenti, perfetta per ambienti esterni eleganti.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_PALISSADE-CORD_pNg3kfVR66.jpeg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Acciaio verniciato", "Corda sintetica riciclata"],
    recyclable: true,
    lifespan: "15 anni",
  },
  { //cambiato
    id: "84",
    name: "Panca Palissade Cord - vista laterale",
    description: "Vista laterale della Panca Palissade con intreccio in corda, per uso esterno.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_PALISSADE-CORD_jBJpNAhaL.jpeg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Acciaio verniciato", "Corda riciclata"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {
    id: "85",
    name: "Sedia Palissade Cord - vista posteriore",
    description: "Dettaglio della parte posteriore della sedia Palissade, robusta e minimalista.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_PALISSADE-CORD_Go5IQXiGDY.jpeg",
    category: "Arredo",
    sustainabilityScore: 87,
    materials: ["Acciaio", "Corda riciclata"],
    recyclable: true,
    lifespan: "15 anni",
  },
  {//cambiato
    id: "86",
    name: "Sedia pieghevole Traverse - vista frontale",
    description: "Sedia da esterno pieghevole Traverse, compatta ed elegante.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_TRAVERSE_GNzDNFOXv6.jpeg",
    category: "Arredo",
    sustainabilityScore: 85,
    materials: ["Alluminio verniciato", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {//cambiato
    id: "87",
    name: "Sedia Traverse - vista ambientata",
    description: "Sedia pieghevole Traverse in ambientazione esterna, ideale per terrazze e giardini.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_TRAVERSE_3ZgDWw9bhA.jpeg",
    category: "Arredo",
    sustainabilityScore: 85,
    materials: ["Alluminio", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {//cambiato
    id: "88",
    name: "Sedia Traverse - dettaglio struttura",
    description: "Vista dettagliata del meccanismo pieghevole della sedia Traverse.",
    image: "https://img.edilportale.com/product-thumbs/2b_Hay_TRAVERSE_aJuEqtOb3U.jpeg",
    category: "Arredo",
    sustainabilityScore: 85,
    materials: ["Metallo verniciato", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "89",
    name: "Tavolino Vitra - vista ambientata moderna",
    description: "Tavolino Vitra in uno spazio domestico moderno, sobrio e funzionale.",
    image: "https://static.vitra.com/media-resized/YtxxHkOcNfRTZNzy-yiVzAt_qCPFhgH4VxxcDLvKRNw/fill/1440/576/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzk0NTc2MTEvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC84NzA2OTg3NC5qcGc.jpg",
    category: "Arredo",
    sustainabilityScore: 88,
    materials: ["Legno multistrato", "Vernici ecologiche"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "90",
    name: "Sedia Vitra Softshell - colore scuro",
    description: "Sedia imbottita Vitra Softshell, elegante e confortevole per ambienti professionali.",
    image: "https://static.vitra.com/media/asset/9311305/storage/v_fullbleed_1440x/87010091.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Polipropilene riciclato", "Tessuto", "Acciaio"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "91",
    name: "Sedia Vitra Softshell - vista chiara",
    description: "Versione chiara della sedia Vitra Softshell, perfetta per ambienti luminosi.",
    image: "https://static.vitra.com/media/asset/9338720/storage/v_fullbleed_1440x/87010140.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Materiali riciclati", "Acciaio", "Tessuto"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "92",
    name: "Sedia Vitra Softshell - composizione multipla",
    description: "Composizione di più sedie Vitra Softshell, adatta a sale conferenze e sale attesa.",
    image: "https://static.vitra.com/media/asset/9438168/storage/v_fullbleed_1440x/87021233.jpg",
    category: "Arredo",
    sustainabilityScore: 89,
    materials: ["Struttura metallica", "Materiali riciclati"],
    recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "93",
    name: "Tavolo Vitra - ambiente professionale",
    description: "Ampio tavolo Vitra in ambiente lavorativo moderno e sostenibile.",
    image: "https://static.vitra.com/media/asset/9412465/storage/v_parallax_1920x1080/86862158.jpg",
    category: "Arredo",
    sustainabilityScore: 90,
    materials: ["Legno certificato FSC", "Acciaio"],
    recyclable: true,
    lifespan: "25 anni",
  },



  // Aggiunta carta da parati
    {
      id: "94",
     name: "Johara B",
      description: "Carta da parati Johara B con motivo geometrico astratto e colorazioni naturali.",
     image: "https://cdn.tapetender70er.de/media/image/aa/25/0f/Johara-B_451851_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 85,
     materials: ["Carta FSC", "Inchiostri a base d'acqua"],
     recyclable: true,
     lifespan: "10 anni"
    },
    {
      id: "95",
     name: "Johara A",
      description: "Carta da parati Johara A, variante con sfondo chiaro e motivi stilizzati.",
     image: "https://cdn.tapetender70er.de/media/image/c8/96/38/451851_Johara_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 85,
     materials: ["Carta FSC", "Inchiostri a base d'acqua"],
     recyclable: true,
     lifespan: "10 anni"
    },
    {
      id: "96",
     name: "Kenai A",
      description: "Carta da parati Kenai A con disegno grafico dai toni rilassanti.",
     image: "https://cdn.tapetender70er.de/media/image/59/92/75/Kenai-A_864211_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 80,
     materials: ["Carta riciclata", "Pigmenti naturali"],
     recyclable: true,
     lifespan: "8 anni"
    },
    {
      id: "97",
     name: "Kenai",
      description: "Variante Kenai con pattern a onde fluide su tonalità calde.",
     image: "https://cdn.tapetender70er.de/media/image/a7/26/c9/864211-A_Kenai_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 80,
     materials: ["Carta riciclata", "Pigmenti naturali"],
     recyclable: true,
     lifespan: "8 anni"
    },
    {
      id: "98",
     name: "Scala B",
      description: "Carta da parati Scala B con grafica vintage a gradazioni.",
     image: "https://cdn.tapetender70er.de/media/image/0c/9f/17/Scala-B_451821_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 88,
     materials: ["Vinile PVC-free", "Supporto non tessuto"],
     recyclable: false,
     lifespan: "12 anni"
    },
    {
      id: "99",
     name: "Scala A",
      description: "Variante Scala A con motivi grafici a gradiente sfumato.",
     image: "https://cdn.tapetender70er.de/media/image/2e/42/19/Scala-A_451821_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 88,
     materials: ["Vinile PVC-free", "Supporto non tessuto"],
     recyclable: false,
     lifespan: "12 anni"
    },
    {
      id: "100",
     name: "Dandelion Mobile A",
      description: "Carta da parati con motivo di soffioni stilizzati in movimento.",
     image: "https://cdn.tapetender70er.de/media/image/1c/68/fe/Dandelion-Mobile-A_690151_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 90,
     materials: ["Carta FSC", "Inchiostri ecologici"],
     recyclable: true,
     lifespan: "10 anni"
    },
    {
      id: "101",
     name: "Dandelion Mobile",
      description: "Variante chiara di Dandelion Mobile, con design floreale delicato.",
     image: "https://cdn.tapetender70er.de/media/image/91/00/6a/690151-A_Dandelion-Mobile_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 90,
     materials: ["Carta FSC", "Inchiostri ecologici"],
     recyclable: true,
     lifespan: "10 anni"
    },
    {
      id: "102",
     name: "Zag-zig",
      description: "Carta da parati Zag-zig con pattern a zigzag retrò e colorato.",
     image: "https://cdn.tapetender70er.de/media/image/2b/3d/41/462131_Zag-zig_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 75,
     materials: ["Carta patinata", "Colori resistenti alla luce"],
     recyclable: true,
     lifespan: "8 anni"
    },
    {
      id: "103",
     name: "Zag-zig A",
      description: "Variante Zag-zig A con colori pastello e motivi dinamici.",
     image: "https://cdn.tapetender70er.de/media/image/00/03/13/Zag-zig-A_462131_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 75,
     materials: ["Carta patinata", "Colori resistenti alla luce"],
     recyclable: true,
     lifespan: "8 anni"
    },
    {
      id: "104",
     name: "Balder F",
      description: "Carta da parati Balder F con texture naturale e colori tenui.",
     image: "https://cdn.tapetender70er.de/media/image/ab/fc/10/Balder-F_106184_2880x1440@2x.jpg",
      category: "Materiali e superfici",
     sustainabilityScore: 92,
     materials: ["Fibre naturali", "Inchiostri a base d'acqua"],
     recyclable: true,
     lifespan: "12 anni"
    },


    
  {
    id: "105",
   name: "Libreria Aliant",
    description: "Libreria modulare bifacciale in legno massello, perfetta come separatore elegante tra ambienti.",
   image: "https://www.diotti.com/it/media/images/librerie/360097/afg-libreria-aliant-04-00.jpeg",
   category: "Arredo",
   sustainabilityScore: 88,
    materials: ["Legno massello", "Metallo verniciato"],
   recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "106",
   name: "Libreria Betis",
    description: "Sistema libreria componibile che crea divisioni funzionali mantenendo apertura visiva.",
   image: "https://www.diotti.com/it/media/images/librerie/483126/libreria-betis-90.jpeg",
   category: "Arredo",
   sustainabilityScore: 85,
    materials: ["Legno laminato", "Struttura metallica"],
   recyclable: true,
    lifespan: "18 anni",
  },
  {
    id: "107",
   name: "Libreria Airport",
    description: "Libreria dal design contemporaneo che definisce spazi senza chiuderli completamente.",
   image: "https://www.diotti.com/it/media/images/librerie/337185/libreria-airport-001-1.jpeg",
   category: "Arredo",
   sustainabilityScore: 82,
    materials: ["MDF eco-friendly", "Acciaio"],
   recyclable: true,
    lifespan: "15 anni",
  },


  {
    id: "108",
   name: "Sedia Diffrient Smart",
    description: "Sedia ergonomica con meccanismo auto-regolante, progettata per il comfort in autonomia lavorativa.",
   image: "https://it.humanscale.com/userFiles/images/seating/smart/hs-seating-diffrient-smart-studio-Frechette_Silos_181_RT.jpg",
   category: "Arredo",
   sustainabilityScore: 90,
    materials: ["Polimero riciclabile", "Alluminio", "Tessuto tecnico"],
   recyclable: true,
    lifespan: "15 anni",
  },


  {
    id: "109",
   name: "Sedia Ocean",
    description: "Sedia operativa realizzata con plastica riciclata marina, per postazioni di lavoro sostenibili.",
   image: "https://www.leyform.com/ita/sedia-ufficio-operativa/gallery/sedia-in-plastica-per-ufficio-e-laboratorio-ocean-img-08.jpg",
   category: "Arredo",
   sustainabilityScore: 95,
    materials: ["Plastica oceanica riciclata", "Acciaio riciclato"],
   recyclable: true,
    lifespan: "12 anni",
  },


  {
    id: "110",
   name: "Sedia VELA Tango",
    description: "Sedia ergonomica per persone con disabilità, favorisce autonomia e comfort personalizzato.",
   image: "https://www.bodytech.it/wp-content/uploads/2025/03/feature_VELA-Tango-700E-active-medium-1-llimage-s405x9999-q80-fwebp.webp",
   category: "Arredo",
   sustainabilityScore: 85,
    materials: ["Polimero biocompatibile", "Acciaio inox", "Tessuto antibatterico"],
   recyclable: true,
    lifespan: "20 anni",
  },
  {
    id: "111",
   name: "Sedia adattiva Bodytech",
    description: "Seduta specializzata per garantire comfort e autonomia a persone con diverse abilità motorie.",
   image: "https://www.bodytech.it/wp-content/uploads/2023/12/Progetto-senza-titolo-4.jpg",
   category: "Arredo",
   sustainabilityScore: 82,
    materials: ["Schiuma memory", "Struttura regolabile", "Rivestimento tecnico"],
   recyclable: true,
    lifespan: "18 anni",
  }
];
